spring:
  datasource:
    url: jdbc:mysql://localhost:3306/post_service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rlawltjr123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

